### ISSUE TITLE
Incomplete video's caused by mid rolls (ad breaks)

### ISSUE THREAD

**Issue by ghost** [emarsden/dash-mpd-cli#14]

**Comment by emarsden** [comment]
I tried downloading from your manifest (directly from the link here on github) and it seems to work fine; I get a 41-minute MP4 which doesn't seem to contain ads. The manifest contains 3 Periods and dash-mpd-cli is concatenating the content, as expected. 

I will note that dash-mpd-cli doesn't currently have any support for declining to download ads, if they are inserted server-side. I am looking at various ways of allowing the user to filter/rewrite the manifest before downloading, there is a balance to be found between generality and ease of use.

**Comment by emarsden** [comment]
Thanks for your example manifest, it's useful to see what real manifests with dynamic ad insertion look like. 

In the latest release there is an experimental implementation of some MPD rewriting functionality which makes it possible to drop Periods that represent ads from the manifest before downloading. This uses the XSLT stylesheet language for rewriting XML, which is very powerful though not particularly intuitive. There is an example stylesheet that shows how to drop ad Periods based on the URL they point to or on the id name in directory test/fixtures

   https://github.com/emarsden/dash-mpd-cli/blob/main/tests/fixtures/rewrite-drop-dai.xslt

**Comment by emarsden** [comment]
It's now easier to use this rewriting functionality to ignore specific elements; you can specify an XPath expression on the commandline with --drop-elements. See 

   https://emarsden.github.io/dash-mpd-cli/rewriting.html

**Comment by emarsden** [comment]
In the continuous integration scripts for Windows, I use xsltproc from choco. You can just say

    choco install xsltproc

You might find it convenient to use the Docker/Podman container, which has all dependencies preinstalled, and is much safer for you. Here's how to do that:

   https://emarsden.github.io/dash-mpd-cli/container.html
