### ISSUE TITLE
does not work with this manifest

### ISSUE THREAD

**Issue by KraXen72** [emarsden/dash-mpd-cli#20]
manifest:
```
https://cmesk-ott-vod-prep-prot.ssl.cdn.cra.cz/0199/3211/cze-dash-s-axinom-sd1-sd2-sd3-sd4-hd1-hd2-P1BCeo6o.ism/.mpd
```
i'm on windows 10
this is how i am running it:
```
dash-mpd-cli.exe https://cmesk-ott-vod-prep-prot.ssl.cdn.cra.cz/0199/3211/cze-dash-s-axinom-sd1-sd2-sd3-sd4-hd1-hd2-P1BCeo6o.ism/.mpd --cookies-from-browser Firefox --quality best --ffmpeg-location "D:\coding\yt-dlp\ffmpeg-master-latest-win64-gpl-shared\bin\ffmpeg.exe" --mp4decrypt-location "D:\coding\yt-dlp\Bento4-SDK-1-6-0-640.x86_64-microsoft-win32\bin\mp4decrypt.exe" --mkvmerge-location "D:\coding\yt-dlp\mkvtoolnix\mkvmerge.exe" -o test.mkv
```
versions:
```
ffmpeg version N-111859-g3c397a1d46-20230830
mkvtoolnix version 80.0 Roundabout
mp4decrypt version in file path
```

it produces an uplayable mkv file, i cannot play it on VLC with error "VLC could not decode the format " " (No description for this codec)" and the mp4 encoding fails after a while and is corrupted:
![image](https://github.com/emarsden/dash-mpd-cli/assets/21956756/fbd7de71-448d-4160-9aaf-1338bd22f77f)

 this is the info about the mkv file:
![image](https://github.com/emarsden/dash-mpd-cli/assets/21956756/7edab05d-77c2-42ed-9b00-aff51d11f358)
i am also attaching the manifest file:

[manifest.mpd.txt](https://github.com/emarsden/dash-mpd-cli/files/13252161/manifest.mpd.txt)
let me know if you need additonal info, thanks.

**Comment by KraXen72** [comment]
what format do the description keys look like and how can i pass them to the downloader? i can get them from the network tab of the service i used to get this manifest, or from somewhere else if you tell me.

**Comment by emarsden** [comment]
This is not the right place to discuss workarounds for DRM. You might be interested in the forums at videohelp.com.

**Comment by KraXen72** [comment]
okay, thanks.
