### ISSUE TITLE
Just downloading without merging

### ISSUE THREAD

**Issue by reformhaus** [emarsden/dash-mpd-cli#4]
Hi, first of all great tool - works like a charm ;-). 

Is it possible to download all Segments of a DASH-Stream including manifest tranparently without merging them?

**Comment by emarsden** [comment]
I'm glad it's useful! 

This is not currently possible, but would be quite easy to implement. I'll keep this issue open and implement it one day. What's the intended purpose (I would think e.g. DRM decoding works on the merged audio and video streams)?

**Comment by reformhaus** [comment]
That sounds good :). I need the feature for development in the context of DASH Just-In-Time Packaging (JITP). I can then use it to control dynamically generated dash streams locally and do manifest manipulation for testing.

**Comment by emarsden** [comment]
In fact, with the existing --keep-audio and --keep-video commandline options, you can access the audio and video files (assuming of course they are separate media streams). I could also add an option to disable muxing, which presumably would imply keep-audio and keep-video.

**Comment by emarsden** [comment]
There is support for this in version 0.1.12. If the design of this interface can be improved, let me know.

   `--save-fragments <FRAGMENTS-DIR>`

**Comment by emarsden** [comment]
I think the --save-fragments argument is not useful to you. 

In the next version, I will fix the warnings shown concerning the deletion of the temporary audio/video files when using --keep-video / --keep-audio. These shouldn't prevent the download from working correctly, though. 

If you have specified --video-only you should not be seeing an attempt to mux. I don't on Linux.

To summarize, to keep only video:

   dash-mpd-cli -v --video-only --keep-video keptvideo.mp4 mpd

To keep only audio:

   dash-mpd-cli -v --audio-only --keep-audio keptaudio.mp4 mpd
