### ISSUE TITLE
Issue with Clearkey encoded audio

### ISSUE THREAD

**Issue by richardjdunn** [emarsden/dash-mpd-cli#73]
Hi there!  Absolutely love this tool, thank you so much.  (also if there is somewhere I can donate some $ as a thank you, let me know).

I'm having an issue with some Clearkey encoded media.  I believe I have the correct decryption key, and everything works as expected (including seeing the correct video), but there is no audio.  I did a bunch of debugging, and the audio that is downloaded *seems* right (ffprobe shows the right length) but it's just... wrong.  When I try to convert it using ffmpeg there are just a ton of random errors.  The audio is just fine when I play off the source website in my browser.

dash-mpd-cli shows "ffmpeg stderr: [aac @ 0x137604c70] channel element 2.9 is not allocated" when it tries to mux.
ffprobe shows the same error when I save just the audio and try to use that command on it

Have you seen anything like this before?  Thanks again!

**Comment by emarsden** [comment]
I probably can't help much here. Two suggestions: 

- The key might be incorrect. I suspect that the stream duration metadata is not encrypted, so ffprobe showing valid information for duration and codecs is not a valid indication that the key is correct. I also don't know of any method to determine whether a decryption key is valid other than checking whether a stream can be decoded/played. 

- You might try with another muxing application, such as mkvmerge, with a different container format like mkv. Or check that you have the latest ffmpeg version. Some streams don't mux/play with certain muxers and work with others.

**Comment by richardjdunn** [comment]
Looks like it was actually an issue with mp4decrypt.  I had done some research and I guess shaka just handles more stuff.  I switched to shaka and it's working now.  Thank you again!
