### ISSUE TITLE
Audio not succesfully intergraded whit video

### ISSUE THREAD

**Issue by Timtta** [emarsden/dash-mpd-cli#77]
this is cause there are 16 video segments
16 subtitle segments
and
17 audio segments

**Comment by emarsden** [comment]
I don't think I've ever seen that. It's probably allowed, if the audio segments are shorten than the video segments and the total audio duration is the same as the total video duration, but I expect the muxers would work in that situation. 

You can try with another muxer helper (see the --muxer-preference commandline argument). 

If you can share the MPD URL or MPD contents I can take a look.

**Comment by Timtta** [comment]
whell i can share it but i cant asure you you can directly watch the livestream (geo-restricted)
base url = https://npo.nl/start/live?channel=NPO3
mpd url = https://npo-nl-ams-p19-am5.cdn.streamgate.nl/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3MjA1MzMzMTAsInVyaSI6IlwvbGl2ZVwvbnBvXC91XzNfNFwvbnBvXC9kcm1cL2Rhc2hfY2VuY1wvbnBvLTNcLzBcLzBcLzBcL25wby0zLmlzbWwiLCJjbGllbnRfaXAiOiI0NS4xNDIuMjM0LjEyNCIsInZpZXdlciI6InZpZXdlciIsInJpZCI6ImNkYTUxNWUifQ.1Oy-uzpSA9y7N1vtCxt5JyqW_PoQUatjPJ7o8jJsV-c/live/npo/u_3_4/npo/drm/dash_cenc/npo-3/0/0/0/npo-3.isml/stream.mpd
key = 8d3c85fa30730fdc39efc09de476415f:8fdccd948bb2cc6d99d5305ccffebcb7
its geo restricted to the Netherlands

**Comment by Timtta** [comment]
error: a value is required for '--muxer-preference <CONTAINER:ORDERING>' but none was supplied
sorry that im dumb what what needs to be in CONTAINER and ORDENING

**Comment by emarsden** [comment]
Make sure you have mkvmerge (from the MKVToolnix suite) installed and try

--muxer-preference mkv:mkvmerge -o mydownload.mkv

(this will download to a file called mydownload.mkv in Matroska format).

I can't currently test that manifest.

**Comment by Timtta** [comment]
17:39:59  INFO   Muxer preference for mkv is ["mkvmerge"]
17:39:59  INFO   Trying muxer mkvmerge
17:39:59  WARN   Muxing with mkvmerge subprocess failed: I/O error spawning mkvmerge subprocess (Error { kind: NotFound, message: "program not found" })
17:39:59  WARN All muxers failed
17:39:59  WARN   unmuxed audio stream: C:\Users\timta\AppData\Local\Temp\dashmpd-audioG7xLhZp.mkv
17:39:59  WARN   unmuxed video stream: C:\Users\timta\AppData\Local\Temp\dashmpd-videojlSlAa7.mkv
17:39:59 ERROR Download failed: muxing error "all muxers failed"

then when i opened those files manualy i notised the little delay in audio video

**Comment by emarsden** [comment]
You don't seem to have installed mkvmerge, or at least it's not in your PATH. But that's probably not the real problem if you see a delay when loading the two streams manually, I'll try to access this MPD.

**Comment by Timtta** [comment]
thanks the delay is the problem like you first see a big BOOM! schreen and then 1 sec later you hear BOOM! like that

**Comment by emarsden** [comment]
This is a "live" / "dynamic" manifest, and dash-mpd-rs doesn't currently have very good support for downloading content from these. In fact it hardly downloads any segments when I tried the channel you showed. I might try to improve that support one day, but probably not soon. You might have more luck with VLC.

**Comment by Timtta** [comment]
whell for me it allready whould help if a feature exists that whould (mayby expirimental) allow you to manualy set a delay of segments from audio, video or subtitles

**Comment by Timtta** [comment]
i got it convertering directly with ffmpeg was sollution
