### ISSUE TITLE
Doesn't work for this URL, have tested on different machines

### ISSUE THREAD

**Issue by MVasuki1** [emarsden/dash-mpd-cli#8]
https://goplay.ml/stream/stream_dash.mpd?d=4jlke2HdAvYk86LzUBvD1U6N73y0Q6N9GsQevtlymTXgo7IpRIF0gmJddiZlZqggxGLBiu9oMX+m14dfT07hVqDLi56bfKr9O2QtOish3BYirETJhFbMUj8O9t9ZeZyjvXVMTGaBv3ICY/0uTqw6XiGrXzkOKfORRwgqAGhQiE1iJvL6RoQEYmxPMBSE1lwEQlK3I5CePzV8UB1XpGMJUc+AfIhHUmPe3JCJ1hAC+RMTMQa8RkVAvEtub7WYjDsU/o4DKhJa76D3uzbxQ5OwrCipiTZ8wAIVdmKQdCJnaFQ=

Url obtained by running network sniffer while playing episode 1 with server 1 selected
https://goplay.ml/4b2d3734373035333434/Apple-of-My-Eye/Episode-1/

**Comment by emarsden** [comment]
Please note that recent versions of dash-mpd-cli are able to decrypt media that have ContentProtection, as long as the mp4decrypt commandline application is installed. See the --key commandline option.
