### ISSUE TITLE
metadata

### ISSUE THREAD

**Issue by 3052** [emarsden/dash-mpd-cli#81]
can you modify the resultant media metadata somehow?

**Comment by emarsden** [comment]
That will depend on your operating system, but see 

  https://www.lesbonscomptes.com/pages/extattrs.html

**Comment by 3052** [comment]
WTF is that URL? I am talking about like the movie title or release date, stuff like that

**Comment by emarsden** [comment]
I was talking about modifying the "extended attribute" metadata on the media file, where dash-mpd-cli puts the download URL, and the title and copyright information if they are specified in the MPD. This is only supported on Linux and MacOS. 

I guess you mean the container-specific metadata. There is no support for modifying this in dash-mpd-cli; what you can store depends on the container (MP4, MKV etc.) and it seems better to modify it with a dedicated tool.

**Comment by 3052** [comment]
dash-mpd-cli is already calling external tool for decryption, so maybe a similar option could be available for metadata?

**Comment by emarsden** [comment]
It would be possible to implement this, but rather fiddly due to the differences in supported metadata fields for the different output containers that dash-mpd-cli can generate. I'll note it as a wishlist item.
