### ISSUE TITLE
How to run this on UNRAID

### ISSUE THREAD

**Issue by Doktor-X** [emarsden/dash-mpd-cli#86]
Hi, so im not all that much familiar with docker and i know only basic stuff.
So i have Unraid server and i manage to install this docker and i can execute it using terminal but i cant save file to /content locatation
![1](https://github.com/user-attachments/assets/240d9a5c-c1ce-4235-aad5-696011b6662d)
![2](https://github.com/user-attachments/assets/3ac47f44-f399-4065-a90d-8cb7faabb436)
![3](https://github.com/user-attachments/assets/ffaaa357-8e2e-4aa1-8f75-1a4ade2fc770)

**Comment by emarsden** [comment]
I've never used Unraid, so can't really help you. It does look like the download succeeded from the terminal screenshot (though there are perhaps additional lines below what you show that confirm that). Is the output file not visible in /mnt/cache/Downloads/index/ ?

**Comment by Doktor-X** [comment]
after some digging i have found out that when i run docker run command i actually runing one time instance that is deleted when its finish hence --rm argument

but i cant figure out how to run version that i have pull from repo
whatever i try i get 
Unable to find image locally

**Comment by emarsden** [comment]
"docker run" creates a container process, that you see with "docker ps". The "--rm" means shut down that process when the command is finished. It doesn't delete either output files (as long as they were written to the host, rather than to the container) nor the cached container image itself. At least, that's how things work with Podman. 

Your screenshot doesn't show exactly what commands you entered to see "Unable to find image locally".

**Comment by Doktor-X** [comment]
I finally succeeded
so i purged all traces of dash mpd cli and after that i run 
docker run command from beggining and i mapped with "-v" my download directory to /content directory of container and now im able to download files
only problem is that i dont have any progress bar so i dont know how long will download last

so my command is "docker run --rm -v /mnt/cache/Downloads/index:/content ghcr.io/emarsden/dash-mpd-cli -v https://xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/manifest.mpd -o test.mp4 --quality best"

**Comment by emarsden** [comment]
OK, great. The progress bar requires an active terminal implementation. You can perhaps try by passing "--tty" to docker (after "--rm") or by running interactively with "-ti" in front of ghcr.io/emarsden/dash-mpd-cli.

**Comment by Doktor-X** [comment]
thanks man, i made it to work now withoup problem, i also made small hash script so that i only enter url location and file name and all is then automated

#!/bin/bash 
echo "Unesi URL:" 
read url 
echo "Naziv datoteke:" 
read ime 
docker run --rm --tty -v /mnt/cache/Downloads/index:/content ghcr.io/emarsden/dash-mpd-cli -v $url -o $ime --quality best
