### ISSUE TITLE
Downloads broken with dash-mpd-cli versions after  0.1.13 bug?

### ISSUE THREAD

**Issue by WebDLLover** [emarsden/dash-mpd-cli#9]
Hi emarsden i tried to download a video with the latest version and it kept getting stuck doing nothing sometimes it downloads audio only very slow but gets stuck on the video so i went to the site to check if they changed something but i saw nothing then i tried different mpd links from other titles even the ones wich previously downloaded succesfully ofcourse with a early version of dash-mpd-cli but same problem i even tried versions before the latest version and after 0.1.13 but same issue so something has broken the downloads looks like not 100% sure but downloads went always fine untill today i went to see when the last time was i downloaded something from here and that was on 02/07 so currently i'am using dash-mpd-cli version 0.1.13 wich works fine as usual i was not getting any error to wich is weird when i have put verbose on one of the versions after 0.1.13 it reached audio segment 666 and said something with timed out on the end of the error i have put a mpd link example underneat if needed

mpd link https://pubads.g.doubleclick.net/ondemand/dash/content/2615619/vid/10148628177752527/GRQ/streams/0e7356c8-8a7c-47f6-9717-7f4c0a8f0fbd/manifest.mpd the mpd link might be geoblocked i think and might need a belgian ip (Belgium) i can provide credentials or a vpn if needed thanks in advance

**Comment by emarsden** [comment]
I haven't noticed problems with my test MPD links. I am able to download your link, which has 3 periods and 368MB in the lowest quality, at around 1MB/s with v0.2.2 which was released today. If you can point to differences in download speed on a public and non geoblocked manifest, I can investigate.

**Comment by emarsden** [comment]
I'm not seeing this here. 

You need to consider that a lot of media streaming content is served by content delivery networks, which can be quite aggressive in caching popular content on an edge node. So a second download of a stream a little after the first download is likely to be much faster. Does your result change if you download first with the old version, then with the new? 

Here for example is a manifest where I see quite strong edge caching effects 

   https://cdn.bitmovin.com/content/assets/bbb/stream.mpd

and here is a stream which doesn't seem to be CDN-served (needs "--ignore-content-type") 

  https://dvb-2017-dm.s3.eu-central-1.amazonaws.com/SL-HDR2.mpd
