### ISSUE TITLE
Can't access video file via Podman 

### ISSUE THREAD

**Issue by shoval6** [emarsden/dash-mpd-cli#90]
Hi,

This is the first time I'm using Podman and containers (windows 10).
In PowerShell I run :
podman machine start (optional step, only required on Windows and MacOS)
podman run --rm -v .:/content ghcr.io/emarsden/dash-mpd-cli -v <MPD-URL> -o foo.mp4

![Screenshot_1](https://github.com/user-attachments/assets/71537cb4-0fbd-4ca5-819b-c153217936df)

After the process, I cant access to the content folder where the file is supposed to be there.
There is no container that running, just the image is exist.
In addition, when i tried to run a container from the image the status always is 'exited'.
I tried some solutions with chatgpt , but nothing works.

Thanks.

**Comment by emarsden** [comment]
Several issues here:

- You seem to be running this as Administrator, which is not normally recommended. You should make a normal user account and use that. 
- You are running from a system directory, which is not writable, so podman will not be able to write output. If you create a normal user account, run podman from your home or Video directory for example. 
- It looks like this manifest is using DRM, but you didn't provide decryption keys (see the warning line near the end). If there is a video output file, it won't be playable.

**Comment by shoval6** [comment]
Thank you for the fast reply.
Just to make sure, I have one user on pc as Administrator , I need to create another one and run PowerShell without Administrator permissions ?
Can you explain practically how to access the content folder and copy the file to my computer ?
I saw the warning line about the DRM, there is an option to get the decryption keys ?

Thanks again.

**Comment by emarsden** [comment]
Creating a normal (non-Administrator) account is recommended on Windows to help protect you from malicious applications you might download. That's not directly relevant to your problem however. 

Obtaining DRM keys is possibly illegal in certain countries, and isn't something we can discuss here. You may like to read the information on the forums at videohelp.com. 

The other problem is that you should start PowerShell in one of your user directories, that you can write to. After starting PowerShell, type something like 

`cd c:/users/Administrator/Video `

If you aren't able to do that, I recommend you find a tutorial on running commandline applications in Windows.

**Comment by shoval6** [comment]
I tried but the same problem happens.
After downloading the video , the container is deleted. I tried to create another container from the same image but the status is "exited" and from that point you can't do nothing.
![Screenshot_2](https://github.com/user-attachments/assets/3f18ee14-79ab-41c4-8d30-fc709386ad45)
![Screenshot_3](https://github.com/user-attachments/assets/85d57ee5-32fc-4ab1-989d-524a9ffacdd8)

**Comment by emarsden** [comment]
The container is supposed to stop after having downloaded the content; all this is expected. You are supposed to have an output MP4 file in the current directory. However, you are testing with a manifest that has DRM, and this may interfere with proper operation. 

I suggest you test with a DASH manifest without DRM, here for example. 

https://vod-dash-ww.live.cf.md.bbci.co.uk/usp/auth/vod/piff_abr_full_hd/87c69e-p0hxfjn6/vf_p0hxfjn6_aa08cd7d-34cf-4985-a4f6-ccb27aedf662.ism/pc_hd_abr_v2_dash_master.mpd?Expires=1727874012&Signature=MlyHeom06PqaqtwVPXkFfJcvHn8i0E1Sh0vuEqhu4w3isQTvpJ7gAj2TaZy1i91Lmyl80TE6l9I7Xh4NqsaOdBg6eBNwJWAxOxgkyby62IVf0Ceo00vDi2yoqUeMiFHYzRAqroIMMkqkf-azUZ55-fUklWtwX8NeB7C7k7XKo0BqiKy1ISmeBut5duiw7E~u94WtEP41~kmXcXLWmv5IQUpN91HyLp-x8MWtBXU8HzgjkRS6uNlufcTB5lRksjN4dS7fj0tQoPYbKy6KSwq7QxgPCtGUdOMerJFBUJPBhqcGpTTOw9SiIR7JtQPYjB3Bml4QUOG5fO9DlCFw0rsEvg__&Key-Pair-Id=K2VWLYKQ4HU1FJ
